default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mogra_twitter_server_development

production:
  <<: *default
  socket: /var/lib/mysql/mysql.sock
  database: mogra_twitter_server_production