source 'https://rubygems.org'

gem 'rails', '4.1.7'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.3'
gem 'compass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', :group => :doc
gem 'unicorn'
gem 'jquery-rails'
gem 'jquery-easing-rails'
gem 'coffee-rails', '~> 4.0.0'
gem "rails_config"
gem 'eventmachine'
gem 'tweetstream'
gem 'guard-livereload'

group :production do
  gem 'therubyracer'
  gem 'execjs'
end
